n=int(input('Digite um numero:'))
n1=(n*1)
n2=(n*2)
n3=(n*3)
n4=(n*4)
n5=(n*5)
n6=(n*6)
n7=(n*7)
n8=(n*8)
n9=(n*9)
n10=(n*10)
print('A tabuada de {}, é:'.format(n))
print('{}'.format(n1))
print('{}'.format(n2))
print('{}'.format(n3))
print('{}'.format(n4))
print('{}'.format(n5))
print('{}'.format(n6))
print('{}'.format(n7))
print('{}'.format(n8))
print('{}'.format(n9))
print('{}'.format(n10))
